Develop
notbadcodecom/java-explore-with-me pull request #3
Opened 2022-11-18 08:39 UTC by notbadcodecom

2022-11-19 19:13 UTC, krylov-sergey-sergeevich requested changes
Привет, отличная работа видно что постарались, оставил некоторые замечания/предложения можно что то по ним улучшить или обсудить =)

2022-11-19 19:13 UTC, krylov-sergey-sergeevich commented on server/src/main/java/com/notbadcode/explorewithme/category/CategoryAdminController.java
> +        log.info("{}", ControllerLog.createUrlInfo(request));
Задумка и реализация отличная, рекомендую почитать про аспекты может быть понравится и сможешь сделать аспект который автоматически будет на методах контроллерах определенных логгинг делать =)

2022-11-19 19:13 UTC, krylov-sergey-sergeevich commented on README.md
> +# Explore With Me project
Отличное описание проекта

2022-11-19 19:13 UTC, krylov-sergey-sergeevich commented on server/src/main/java/com/notbadcode/explorewithme/category/CategoryDto.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
Не переусложнение? Можно же и самому поставить модификаторы

2022-11-19 19:13 UTC, krylov-sergey-sergeevich commented on server/src/main/java/com/notbadcode/explorewithme/category/CategoryMapper.java
> +public class CategoryMapper {
Рекомендую почитать на будущее про Mapstruct, сейчас тут его применять излишне

2022-11-19 19:13 UTC, krylov-sergey-sergeevich commented on server/src/main/java/com/notbadcode/explorewithme/category/CategoryServiceImpl.java
> +    public EventCategory getCategoryOr404Error(Long categoryId) {
В название не рекомендую писать вот такие штуки: Or404Error, это можно подразумевать вот такими способами
Регулируя названия методов:
get - или отдает или ошибку кидает
find или отдает или null возвращает

2022-11-19 19:13 UTC, krylov-sergey-sergeevich commented on server/src/main/java/com/notbadcode/explorewithme/category/CategoryServiceImpl.java
> +        this.eventService = eventService;
Нехорошо что получилась циклическая зависимость есть различные подходы ее разруливания, но иногда и вправду это не решается

2022-11-19 19:13 UTC, krylov-sergey-sergeevich commented on server/src/main/java/com/notbadcode/explorewithme/category/EventCategory.java
> +public class EventCategory {
Есть ощущение что можно меньшим кол-во аннотаций сверху обойтись =)

2022-11-19 19:13 UTC, krylov-sergey-sergeevich commented on server/src/main/java/com/notbadcode/explorewithme/compilation/Compilation.java
> +public class Compilation {
Есть ощущение что можно меньшим кол-во аннотаций сверху обойтись =)

2022-11-19 19:13 UTC, krylov-sergey-sergeevich commented on server/src/main/java/com/notbadcode/explorewithme/compilation/Compilation.java
> +    @ManyToMany(cascade = CascadeType.PERSIST, fetch = FetchType.EAGER)
EAGER - не хорошая практика, надеюсь вам рассказывали, но в для учебного проекта это нормально

2022-11-19 19:13 UTC, krylov-sergey-sergeevich commented on server/src/main/java/com/notbadcode/explorewithme/compilation/CompilationServiceImpl.java
> +    public Compilation getCompilationOr404Error(Long compId) {
Название можно лучше =)

2022-11-19 19:13 UTC, krylov-sergey-sergeevich commented on server/src/main/java/com/notbadcode/explorewithme/compilation/CompilationServiceImpl.java
> +            throw new BadRequestException("Compilation already pinned");
BadRequestException - это обычно кидают когда запрос некорректный или что-то такое грубо говоря пытаются неправильно воспользоваться апи, а тут вроде как бизнес ошибка пытаются сделать что незя, но тут такой момент спорный

2022-11-19 19:13 UTC, krylov-sergey-sergeevich commented on server/src/main/java/com/notbadcode/explorewithme/config/JacksonConfiguration.java
> +    String format;
модификаторы доступа

2022-11-19 19:13 UTC, krylov-sergey-sergeevich commented on server/src/main/java/com/notbadcode/explorewithme/error/ErrorHandler.java
> +public class ErrorHandler {
Хорошо проработано

2022-11-19 19:13 UTC, krylov-sergey-sergeevich commented on server/src/main/java/com/notbadcode/explorewithme/event/Event.java
> +    @WhereJoinTable(clause = "status='CONFIRMED'")
Интересная штука, но если честно слабо представляю насколько эффективно это работает - но красиво

2022-11-19 19:13 UTC, krylov-sergey-sergeevich commented on server/src/main/java/com/notbadcode/explorewithme/event/EventServiceImpl.java
> +        this.formatter = DateTimeFormatter.ofPattern(format);
Может подумать и сделать утилитный класс в котором 1 раз создать этот форматер и использовать везде

2022-11-19 19:13 UTC, krylov-sergey-sergeevich commented on server/src/main/java/com/notbadcode/explorewithme/event/EventServiceImpl.java
> +    public Event getEventOr404Error(Long eventId) {
Название

2022-11-19 19:13 UTC, krylov-sergey-sergeevich commented on server/src/main/java/com/notbadcode/explorewithme/event/EventServiceImpl.java
> +    public EventFullDto findEventById(HttpServletRequest request, Long eventId) {
Название

2022-11-19 19:13 UTC, krylov-sergey-sergeevich commented on server/src/main/java/com/notbadcode/explorewithme/event/EventSort.java
> +        return null;
Обычно кидают исключение, но тут от вкусов зависит

2022-11-19 19:13 UTC, krylov-sergey-sergeevich commented on server/src/main/java/com/notbadcode/explorewithme/participation/ParticipationService.java
> +    Participation getParticipationOr404Error(Long id);
Название метода

2022-11-19 19:13 UTC, krylov-sergey-sergeevich commented on server/src/main/java/com/notbadcode/explorewithme/participation/ParticipationServiceImpl.java
> +public class ParticipationServiceImpl implements ParticipationService {
Есть ощущение что в этом классе можно некоторые штуки сделать так чтобы избежать дублирования кода

2022-11-20 18:28 UTC, notbadcodecom commented on server/src/main/java/com/notbadcode/explorewithme/category/CategoryDto.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
Предполагал однообразие, что бы везде было одинаково.

2022-11-20 18:28 UTC, notbadcodecom commented on server/src/main/java/com/notbadcode/explorewithme/category/CategoryMapper.java
> +public class CategoryMapper {
Спасибо, читал недавно о этой библиотеке, понял зачем, но еще не понял как.

2022-11-20 18:31 UTC, notbadcodecom commented on README.md
> +# Explore With Me project
Спасибо.

2022-11-20 19:26 UTC, notbadcodecom commented on server/src/main/java/com/notbadcode/explorewithme/category/CategoryServiceImpl.java
> +        this.eventService = eventService;
Поправил, добавил нативный SQL-запрос в categoryRepo, больше здесь не нужен eventService.

2022-11-20 20:47 UTC, notbadcodecom commented on server/src/main/java/com/notbadcode/explorewithme/category/EventCategory.java
> +public class EventCategory {
Не понимаю. Не нравится @FieldDefaults(level = AccessLevel.PRIVATE)?
Или вместо @Getter-setter-AllArgsConstructor-NoArgsConstructor нужно было поставить @Data? Но  @Data с @builder - аннотации, которые могут привести к конфликту?

2022-11-20 20:49 UTC, notbadcodecom commented on server/src/main/java/com/notbadcode/explorewithme/error/ErrorHandler.java
> +public class ErrorHandler {
спасибо

2022-11-20 20:53 UTC, notbadcodecom commented on server/src/main/java/com/notbadcode/explorewithme/event/Event.java
> +    @WhereJoinTable(clause = "status='CONFIRMED'")
По идее это лишний запрос were? Мне полностью участники не нужны, только подтвержденные, поэтому, мне кажется, эта аннотация сюда подходит.

2022-11-20 21:12 UTC, notbadcodecom commented on server/src/main/java/com/notbadcode/explorewithme/event/EventSort.java
> +        return null;
наверное исключение лучше, что бы понимали, что запрос плохой, а то пользователь API будет думать, что получил нужные данные.

2022-11-22 23:17 UTC, notbadcodecom commented on server/src/main/java/com/notbadcode/explorewithme/category/CategoryAdminController.java
> +        log.info("{}", ControllerLog.createUrlInfo(request));
Вообще спасибо, интересная штука. Но в проекте я не применил: потому что у меня берутся данные с HttpServletRequest и видно, что он сразу уходит в ControllerLog. А при аспекте я все равно должен указать в сигнатуре метода контроллера  HttpServletRequest , что бы его видел аспект, но тогда не видно куда уходит HttpServletRequest  и мне это не понравилось.

2022-11-24 16:48 UTC, krylov-sergey-sergeevich approved these changes
Привет, достойная работа и радует, что вы узнаете и читаете про дополнительные технологии. Зачет!

2022-11-24 16:48 UTC, krylov-sergey-sergeevich commented on server/src/main/java/com/notbadcode/explorewithme/category/CategoryRepository.java
> +    @Query(value = "SELECT count(e.event_id) > 0 FROM events e WHERE e.category_id = :id",
Лучше реже стараться использовать nativeQuery

2022-11-24 16:48 UTC, krylov-sergey-sergeevich commented on server/src/test/java/com/notbadcode/explorewithme/event/EventServiceImplIntegrationTest.java
> +    HttpServletRequest request;
модификаторы доступа

2022-11-24 16:49 UTC, krylov-sergey-sergeevich approved these changes
Привет, отличная работа видно что постарались, оставил некоторые замечания/предложения можно что то по ним улучшить или обсудить =)

2022-11-24 16:54 UTC, krylov-sergey-sergeevich approved these changes

2022-11-24 16:57 UTC, krylov-sergey-sergeevich approved these changes
Привет, достойная работа и радует, что вы узнаете и читаете про дополнительные технологии. Зачет!

2022-11-24 16:57 UTC, krylov-sergey-sergeevich commented on README.md
> +Сервис для обмена информацией о событиях и поиска учестников
Комментарий чтобы github зачел approve

2022-11-24 18:29 UTC, merged